---
# ====== Application: mtg-tracker ============================
id: 100
identification: 
  name: mtg-tracker
  alias: MTG-TRACKER
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 10346383796907129

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_ARUNEXT

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: mtg-tracker

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 10347147664907138

navigation-bar: 
  implementation: List
  list: Navigation Bar # 10348314037907185
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 46965902093946

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: mtg-tracker

component-settings: 
- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 10341847257907111
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 46965902091757

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 10342108815907115
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 46965902091773

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 10342471475907116
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 46965902091774

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 10342709515907117
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 46965902091774

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 10343031497907118
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 46965902091784

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 10343325654907118
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 46965902091807

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 10343619896907119
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 46965902091831

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 10343908239907120
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 46965902091858

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 10344233434907121
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 46965902091888

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 10344582787907122
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 46965902091915

- # ====== Component Setting: NATIVE_IR ========================
  id: 10344826882907122
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 46965902091942

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 10345128122907123
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 46965902091969

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 10345470986907124
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 46965902091996

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 10345722300907125
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 46965902092028

